# Библиотека Numpy


In [2]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(type(x))

<class 'numpy.ndarray'>


## Вычсиление среднего арифметического значения, используя Numpy

In [3]:
x.mean()

2.0

## Особенности работы с numpy

In [4]:
z = [1, 2, 3] + [4, 5, 6]
print(z)

[1, 2, 3, 4, 5, 6]


In [5]:
b = x + y
print(b)

[5 7 9]


In [7]:
b = x - y
print(b)

[-3 -3 -3]


In [8]:
b = x * y
print(b)

[ 4 10 18]


In [9]:
b = x / y
print(b)

[0.25 0.4  0.5 ]


In [10]:
b = x ** y
print(b)

[  1  32 729]


### Автоматическое наполнение массивов

In [11]:
# аналог range

newNpArray = np.arange(0, 10)
print(newNpArray)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
# создать массив из 10 чисел, заполненных единицами
np.full(10, 1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
# создать матрицу 2х5 из нулей
np.full([2, 5], 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
# объединить массивы в один
a = np.arange(10)
b = np.arange(10, 20)

np.concatenate((a, b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
# перемешать элементы массива
import random

nums = np.arange(10)
random.shuffle(nums)

nums

array([5, 1, 9, 7, 0, 4, 3, 8, 6, 2])

# Библиотека pandas

In [33]:
import pandas as pd

ratings = pd.read_csv('ratings.csv')
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [34]:
ratings.head(10)

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931
5       1       70     3.0  964982400
6       1      101     5.0  964980868
7       1      110     4.0  964982176
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [35]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   userId     100836 non-null  int64  
 1   movieId    100836 non-null  int64  
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64  
dtypes: float64(1), int64(3)
memory usage: 3.1 MB


In [37]:
# сколько стран в коллекции
len(ratings.movieId.unique())

9724

In [38]:
%%time

# топ пользователей по количеству оценок
ratings.groupby('userId').count().sort_values('movieId', ascending=False).head()

CPU times: user 7.32 ms, sys: 2.68 ms, total: 10 ms
Wall time: 14.6 ms


movieId  rating  timestamp
userId                            
414        2698    2698       2698
599        2478    2478       2478
474        2108    2108       2108
448        1864    1864       1864
274        1346    1346       1346

In [42]:
ratings_grouped = ratings.groupby('userId').agg([min, max])
ratings_grouped.head()

movieId         rating        timestamp            
           min     max    min  max         min         max
userId                                                    
1            1    5060    1.0  5.0   964980499   965719662
2          318  131724    2.0  5.0  1445714835  1445715340
3           31   72378    0.5  5.0  1306463323  1306464293
4           21    4967    1.0  5.0   945078428  1007574542
5            1     608    1.0  5.0   847434747   847435337

# Объеденение информации из разных файлов

In [43]:
movies = pd.read_csv('movies.csv')
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [44]:
joined = ratings.merge(movies, on='movieId', how='left')
joined.head()

userId  movieId  rating  timestamp                        title  \
0       1        1     4.0  964982703             Toy Story (1995)   
1       1        3     4.0  964981247      Grumpier Old Men (1995)   
2       1        6     4.0  964982224                  Heat (1995)   
3       1       47     5.0  964983815  Seven (a.k.a. Se7en) (1995)   
4       1       50     5.0  964982931   Usual Suspects, The (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                               Comedy|Romance  
2                        Action|Crime|Thriller  
3                             Mystery|Thriller  
4                       Crime|Mystery|Thriller

In [47]:
import pandas as pd

data = pd.read_html('https://fortrader.org/quotes', encoding='utf8')[1]
data.head(10)

Название    Цена  Изменение  Изменение(%)  \
0       Нефть Brent Курс нефти сегодня   93.46        0.0           0.0   
1          Нефть WTI Цены на нефть WTI   87.52        0.0           0.0   
2  Природный газ Цена на природный газ    5.68        0.0           0.0   
3                                 Кофе  179.65        0.0           0.0   
4                             Кукуруза  685.40        0.0           0.0   
5                                  Соя  411.00        0.0           0.0   
6                               Хлопок   77.71        0.0           0.0   

   Обновлено  
0        NaN  
1        NaN  
2        NaN  
3        NaN  
4        NaN  
5        NaN  
6        NaN